name: Shouqianba Release
on:
  release:
    types:
      - created

env:
  GOLANGCI_VERSION: 'v1.52'

jobs:
  publish-image:
    if: github.repository == 'lujiajing1126/rollouts'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: |
            go.sum
      - name: Code generate
        run: |
          make generate
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        timeout-minutes: 20
        with:
          context: .
          push: true
          tags: |
            ghcr.io/lujiajing1126/rollouts:${{ github.event.release.tag_name }}
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
